config/routes.rb
Rails.application.routes.draw do
  root "cohorts#index"
  resources :pull_request_files
  resources :pull_requests
  resources :students, param: :slug
  resources :cohorts, param: :slug do
    resources :labs, param: :slug
  end

  post "webhooks/pull-requests", to: "webhooks#create"

  get '/search', to: 'searches#new', as: :search

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
require 'csv'
class Cohort < ApplicationRecord
  has_many :students
  has_many :labs

  validates :name, uniqueness: true, presence: true, format: {with: /\A\S+\z/, message: "can't contain spaces"}

  has_attached_file :roster_csv, :path => ":rails_root/public/system/rosters/:filename"
  validates_attachment :roster_csv, content_type: { content_type: ["text/csv", "text/comma-separated-values"] }
  validates_attachment_file_name :roster_csv, :matches => [/csv\Z/]

  def to_param
    self.name
  end


  def create_members
    return if !roster_csv.path
    csv_rows = CSV.foreach(roster_csv.path, headers: true)
    csv_rows.each do |student_row|
      student = Student.find_or_create_from_row(student_row.to_h)
      student.update(cohort: self)
    end
  end

end

app/models/lab.rb
class Lab < ApplicationRecord
  belongs_to :cohort
  has_many :pull_requests
  validates :repo, presence: true, uniqueness: true

  before_create :slugify

  def to_param
    self.slug
  end

  def slugify
    self.slug = self.name.strip.downcase.gsub(" ", "-")
  end

  def files
    filenames = self.pull_requests.map {|pr| pr.pull_request_files}.flatten.pluck(:name).map!(&:downcase).delete_if {|f| f.start_with?("db/") || !f.scan(/_spec/).empty?}
    filenames.map {|filename| filename.split("/").last}.uniq
  end

  def directories
    filenames = self.pull_requests.map {|pr| pr.pull_request_files}.flatten.pluck(:name).map!(&:downcase).delete_if {|f| f.start_with?("spec/")}
    filenames.map {|file| file.split("/")[0..-2].join("/")}.uniq
  end

  def pull_requests?
    !self.pull_requests.empty?
  end

  def repo_name
    self.repo.split("/").last
  end
end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
  belongs_to :lab
  belongs_to :student
  has_many :pull_request_files
end

app/models/pull_request_file.rb
class PullRequestFile < ApplicationRecord
  belongs_to :pull_request
  delegate :student, to: :pull_request

  def filename_without_path
    self.name.split("/").last
  end

  def filepath
    self.name.split("/")[0..-2].join("/")
  end
end

app/models/search.rb
class Search
  include ActiveModel::Model
  attr_accessor :type, :query, :results, :cohort_id
  validates :query, presence: true


  def execute
    if type == 'students'
      student_search
    else
      lab_search
    end
  end

  def student_search
    self.results = Student.where('first_name ILIKE ? OR last_name ILIKE ?', "%#{query}%", "%#{query}%")
  end

  def lab_search
    self.results = Lab.where('name ILIKE ? AND cohort_id = ?', "%#{query}%", cohort_id)
  end

  def results_exist?
    results && !results.empty?
  end

  def for_students?
    type == "students"
  end

  def for_labs?
    type == "labs"
  end

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort
  has_many :pull_requests
  has_many :labs, through: :pull_requests

  before_create :slugify

  def to_param
    self.slug
  end

  def slugify
    self.slug = self.full_name.strip.downcase.gsub(" ", "-")
  end

  def self.find_or_create_from_row(params)
    cols = self.columns.map {|col| col.name}
    params.delete_if {|key| !cols.include?(key)}
    self.find_or_create_by(params)
  end

  def full_name
    "#{self.first_name} #{self.last_name}" 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  def index
    @cohorts = Cohort.all
  end

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      @cohort.create_members
      redirect_to @cohort
    else
      redirect_to new_cohort_path
    end
  end

  def show
    @cohort = Cohort.find_by(name: params[:slug])
  end

  def destroy
  end

  private
    def cohort_params
      params.require(:cohort).permit(:name, :roster_csv,)
    end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController

  before_action :set_cohort

  def index
  end

  def show
    @lab = Lab.find_by(slug: params[:slug], cohort: @cohort)
  end

  def new
    @lab = Lab.new
  end

  def create
    lab = Lab.new(lab_params)
    lab.cohort = @cohort
    if lab.save
      lab.update(deploy_date: (Adapters::GitHubWrapper.new.get_repo_create_date(lab) || Date.today))
      AddLabWebhookJob.perform_now(lab.id)
      redirect_to cohort_lab_path(@cohort, lab)
    else
      redirect_to new_cohort_lab_path(@cohort), flash[:notice] = lab.errors.messages
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def lab_params
      params.require(:lab).permit(:name, :repo, :cohort_id)
    end

    def set_cohort
      @cohort = Cohort.find_by(name: params[:cohort_slug])
    end

    def set_lab
    end
end

app/controllers/pull_request_files_controller.rb
class PullRequestFilesController < ApplicationController
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController

  def create
    @lab = Lab.find_by(slug: params[:lab])
    @pull_requests = PullRequestFetcherJob.perform_now(@lab.id)
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new(type: params[:type], query: params[:query], cohort_id: params[:cohort][:id])
    @search.execute if @search.valid?
    render 'new'
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @student = Student.find_by(slug: params[:slug])
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController

  skip_before_action :verify_authenticity_token, :only => [:create]

  def create
    if params[:zen]
      head :no_content
      return
    else
      pull_request = Adapters::GitHubWrapper.new.create_or_update_pr_from_webhook(params[:pull_request])
      WebHooksPullRequestUpdaterJob.perform_now(pull_request)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/pull_request_files_helper.rb
module PullRequestFilesHelper
end

app/helpers/pull_requests_helper.rb
module PullRequestsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/cohorts/_cohort.html.erb
<div class="col-md-6 cohort-show-child">
<h4>Students</h4>
    <% cohort.students.each do |student| %>
      <li><%=link_to student.full_name, student_path(student)%> // <%=link_to student.github_username, "http://www.github.com/#{student.github_username}"%></li>
    <%end%>
</div>

app/views/cohorts/_form_fields.html.erb
<div clas="form-group">

  <h4>Cohort Name</h4>
  <%= f.text_field :name, class: "form-control", id: "Name" %>

</div>


<div class="form-group">
  <h4 data-container="body" data-toggle="popover" data-placement="bottom" data-content="To download the csv roster for your cohort, visit the cohort's organization on learn.co and click the 'download csv roster' button">Upload Roster CSV*</h4>
      
  <span class="btn btn-success btn-file">
    <%= f.label :upload_csv %>
    <%= f.file_field :roster_csv %>
  </span>
</div>

app/views/cohorts/index.html.erb
<div class="page-header">
  <h1>Cohorts <small><%=link_to "add cohort", new_cohort_path, class: "btn btn-default"%></small></h1>
</div>

<h1 id="cohort-title">Cohorts</h1>
<div class="well">
  <ul class="cohort-index">
    <% @cohorts.each do |c| %>
     <li><h2><%= link_to c.name, cohort_path(c) %></h2></li>
    <% end %>
  </ul>
</div>

app/views/cohorts/new.html.erb
<div style="text-align: center;">
  
  <h1>Add your cohort</h1>
  <div class="alert alert-dismissible alert-success">
    <p>cohort name should match the name of the cohort's GitHub repo.</p>
    <p>for example, if the cohort's repo '/learn-co-curriculu/web-1115',</p>
    <p>name your cohort 'web-1115'</p>
  </div>
  
  <div class="form-horizontal">
    <%= form_for @cohort do |f| %>
      <%= render partial: 'form_fields', locals: {f: f} %>
      <%= f.submit "Create Cohort", class: "btn btn-primary", style: "width: 100%; margin-top: 20px" %>
    <% end %>
  </div>
</div>  

app/views/cohorts/show.html.erb
<div class="page-header">
  <h1><%= @cohort.name %><%= link_to "new lab", new_cohort_lab_path(@cohort), class: "btn btn-default", id: "new-lab-btn"%></h1>
</div>

<div class="col-md-12 cohort-well"> 
  <div class="col-md-6 cohort-show-child">
    <h4>Students</h4>
    <%= render partial: "students/student", collection: @cohort.students %>
  </div>

  <div class="col-md-6 cohort-show-child">
    <h4>Labs</h4>
    <%= render partial: "labs/lab", locals: {cohort: @cohort }, collection: @cohort.labs.sort_by {|l| l.deploy_date} %>
  </div>
</div>

app/views/labs/_flash_error.html.erb
<% if flash[:notice]%>

  <div class="alert alert-danger" role="alert" style="margin-top: 2%">
    <% flash[:notice].each do |type, messages| %>
      <%messages.each do |m|%>
         <%=type%> <%=m%>
      <%end%>
    <%end%>
  </div>
<%end%>

app/views/labs/_lab.html.erb
<li><%= link_to lab.name, cohort_lab_path(cohort, lab) %></li>

app/views/labs/_lab_directories.html.erb
<div class="panel">
  <div class="panel-heading">
    <h1 class="panel-title">Select Directories to view  
      <button class="btn btn-info rotate-reset" data-menu="lab-directories" id="select-lab-content-btn"><span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
    </h1>
  </div>
  <div data-id="lab-directories">
    <ul class="lab-select-list">
    <%lab.directories.each do |d|%>
      <li><input class="file-checkbox" type="checkbox" data-id="selected-directories" value="<%=d%>"> <%=d%></li>
    <%end%>
    </ul>
    <div class="lab-select-submit-btn" data-submit="directories">
      <button class="btn btn-info">submit</button>
    </div>
  </div>
</div>

app/views/labs/_lab_files.html.erb
<div class="panel">
  <div class="panel-heading">
    <h1 class="panel-title">Select files to view  
      <button class="btn btn-info rotate-reset" data-menu="lab-files" id="select-lab-content-btn"><span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
    </h1>
  </div>
  <div data-id="lab-files" style="display: none;">
    <ul class="lab-select-list">
    <%lab.files.each do |f|%>
      <li><input class="file-checkbox" type="checkbox" data-id="selected-files" value="<%=f%>"> <%=f%></li>
    <%end%>
    </ul>
    <div class="lab-select-submit-btn">
      <button class="btn btn-info" data-submit="files">submit</button>
    </div>
  </div>
</div>

app/views/labs/_pull_requests_list.html.erb
<%if lab.pull_requests?%>
  <%lab.pull_requests.each do |pull_request|%>
      <li>
        <h3><%= link_to pull_request.student.full_name, student_path(pull_request.student) %></h3>
      </li>
      <%= render partial: "pull_requests/pull_request", locals: {pull_request: pull_request} %>

  <%end%>
<%end%>

app/views/labs/new.html.erb
<div class="page-header">
  <h1 id="lab-header">new lab <small><%=@cohort.name%></small></h1>
</div>

<%= form_for [@cohort, @lab] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control"%>

  <%= f.label :repo %>
  <%= f.text_field :repo, class: "form-control" %>
  <br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<%= render partial: "labs/flash_error"%>

app/views/labs/show.html.erb
<div class="page-header">
  <h1 id="lab-header"><%= link_to @lab.name, @lab.repo, target: "blank" %><%= link_to "get pull requests", pull_requests_path({lab: @lab}), method: "post", remote: true, class: "btn btn-default", id: "get-prs-btn"%> <button class="btn btn-info" id="show-all-prs">show all</button></h1>
</div>


<div id="file-select">
  <%= render partial: "labs/lab_files", locals: {lab: @lab}%>
</div>

<div id="directory-select">
  <%= render partial: "labs/lab_directories", locals: {lab: @lab}%>
</div>

<ul id="pull_request_list">
  <%= render partial: "labs/pull_requests_list", locals: {lab: @lab}%>
</ul>

app/views/pull_request_files/_pull_request_file.html.erb
<div class="panel panel-default student-<%= pull_request_file.student.id %>" data-class="pr-file" data-files="<%=pull_request_file.filename_without_path%>" data-directories="<%=pull_request_file.filepath%>"data-student="<%=pull_request_file.student.id%>" data-pr-parent="<%=pull_request_file.pull_request.id%>">
  <div class="panel-heading"><h4 class="panel-title"><%=pull_request_file.name %></h4></div>
  <div class="panel-body">
   <pre class="prettyprint lang-ruby linenums"><code><%= pull_request_file.content %></code></pre>
  </div>
</div>

app/views/pull_requests/_pull_request.html.erb
  <button data-id="student-<%= pull_request.student.id %>" data-pr="<%=pull_request.id%>", class="btn btn-info show-pr">show PR</button>
  <%=link_to "view on GitHub", pull_request.url, target: "blank", class: "btn btn-success"%>
  <ul>
    <%= render partial: "pull_request_files/pull_request_file", collection: pull_request.pull_request_files %>
  </ul>

app/views/pull_requests/create.js.erb
$("#pull_request_list").html("<%= j render partial: 'labs/pull_requests_list', locals: {lab: @lab}%>")
$("[data-class='pr-file'").hide();
 PR.prettyPrint() 

app/views/searches/new.html.erb
<h1>Search Results: <%= @search.type.capitalize %></h1>
<% if @search.results_exist? %>
  <ul>
  <% @search.results.each do |result| %>
    <% if @search.for_students? %>
    <li><%= link_to result.full_name, student_path(result) %></li>
    <% elsif @search.for_labs? %>
    <li><%= link_to result.name, cohort_lab_path(result.cohort, result) %></li>
    <% end %>
  <% end %>
  </ul>
<% else %>
  <p>No <%= @search.type %> matching your query. Please revise your search term.</p>
<% end %>

app/views/students/_student.html.erb
<li><%=link_to student.full_name, student_path(student)%> // <%=link_to student.github_username, "http://www.github.com/#{student.github_username}"%></li>

app/views/students/show.html.erb
<div class="page-header">
  <h1><%= @student.full_name %> // <small><%=link_to @student.github_username, "http://github.com/#{@student.github_username}"%></small></h1>
</div>

<div class="row">
  <ul id="pull_request_list">
    <%@student.pull_requests.sort_by {|pr| pr.lab.deploy_date}.each do |pr|%>
      <li><h3><%=pr.lab.name%></li></h3>
      <%= render partial: 'pull_requests/pull_request', locals: {student: @student, pull_request: pr}%>
    <%end%>
  </ul>

</div>