config/routes.rb
Rails.application.routes.draw do
  root "cohorts#index"
  resources :pull_request_files
  resources :pull_requests
  resources :students, param: :slug
  resources :cohorts, param: :slug do
    resources :labs, param: :slug
  end

  post "webhooks/pull-requests", to: "webhooks#create"

  get '/search', to: 'searches#new', as: :search

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
require 'csv'
class Cohort < ApplicationRecord
  has_many :students
  has_many :labs

  validates :name, uniqueness: true, presence: true, format: {with: /\A\S+\z/, message: "can't contain spaces"}

  has_attached_file :roster_csv, :path => ":rails_root/public/system/rosters/:filename"
  validates_attachment :roster_csv, content_type: { content_type: ["text/csv", "text/comma-separated-values"] }
  validates_attachment_file_name :roster_csv, :matches => [/csv\Z/]

  def to_param
    self.name
  end


  def create_members
    return if !roster_csv.path
    csv_rows = CSV.foreach(roster_csv.path, headers: true)
    csv_rows.each do |student_row|
      student = Student.find_or_create_from_row(student_row.to_h)
      student.update(cohort: self)
    end
  end

end

app/models/lab.rb
class Lab < ApplicationRecord
  belongs_to :cohort
  has_many :pull_requests
  validates :repo, presence: true, uniqueness: true

  before_create :slugify

  def to_param
    self.slug
  end

  def slugify
    self.slug = self.name.strip.downcase.gsub(" ", "-")
  end

  def files
    filenames = self.pull_requests.map {|pr| pr.pull_request_files}.flatten.pluck(:name).map!(&:downcase).delete_if {|f| f.start_with?("db/") || !f.scan(/_spec/).empty?}
    filenames.map {|filename| filename.split("/").last}.uniq
  end

  def directories
    filenames = self.pull_requests.map {|pr| pr.pull_request_files}.flatten.pluck(:name).map!(&:downcase).delete_if {|f| f.start_with?("spec/")}
    filenames.map {|file| file.split("/")[0..-2].join("/")}.uniq
  end

  def pull_requests?
    !self.pull_requests.empty?
  end

  def repo_name
    self.repo.split("/").last
  end
end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
  belongs_to :lab
  belongs_to :student
  has_many :pull_request_files
end

app/models/pull_request_file.rb
class PullRequestFile < ApplicationRecord
  belongs_to :pull_request
  delegate :student, to: :pull_request

  def filename_without_path
    self.name.split("/").last
  end

  def filepath
    self.name.split("/")[0..-2].join("/")
  end
end

app/models/search.rb
class Search
  include ActiveModel::Model
  attr_accessor :type, :query, :results, :cohort_id
  validates :query, presence: true


  def execute
    if type == 'students'
      student_search
    else
      lab_search
    end
  end

  def student_search
    self.results = Student.where('first_name ILIKE ? OR last_name ILIKE ?', "%#{query}%", "%#{query}%")
  end

  def lab_search
    self.results = Lab.where('name ILIKE ? AND cohort_id = ?', "%#{query}%", cohort_id)
  end

  def results_exist?
    results && !results.empty?
  end

  def for_students?
    type == "students"
  end

  def for_labs?
    type == "labs"
  end

end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort
  has_many :pull_requests
  has_many :labs, through: :pull_requests

  before_create :slugify

  def to_param
    self.slug
  end

  def slugify
    self.slug = self.full_name.strip.downcase.gsub(" ", "-")
  end

  def self.find_or_create_from_row(params)
    cols = self.columns.map {|col| col.name}
    params.delete_if {|key| !cols.include?(key)}
    self.find_or_create_by(params)
  end

  def full_name
    "#{self.first_name} #{self.last_name}" 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  def index
    @cohorts = Cohort.all
  end

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      @cohort.create_members
      redirect_to @cohort
    else
      redirect_to new_cohort_path
    end
  end

  def show
    @cohort = Cohort.find_by(name: params[:slug])
  end

  def destroy
  end

  private
    def cohort_params
      params.require(:cohort).permit(:name, :roster_csv,)
    end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController

  before_action :set_cohort

  def index
  end

  def show
    @lab = Lab.find_by(slug: params[:slug], cohort: @cohort)
  end

  def new
    @lab = Lab.new
  end

  def create
    lab = Lab.new(lab_params)
    lab.cohort = @cohort
    if lab.save
      lab.update(deploy_date: (Adapters::GitHubWrapper.new.get_repo_create_date(lab) || Date.today))
      AddLabWebhookJob.perform_now(lab.id)
      redirect_to cohort_lab_path(@cohort, lab)
    else
      redirect_to new_cohort_lab_path(@cohort), flash[:notice] = lab.errors.messages
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def lab_params
      params.require(:lab).permit(:name, :repo, :cohort_id)
    end

    def set_cohort
      @cohort = Cohort.find_by(name: params[:cohort_slug])
    end

    def set_lab
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new(type: params[:type], query: params[:query], cohort_id: params[:cohort][:id])
    @search.execute if @search.valid?
    render 'new'
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @student = Student.find_by(slug: params[:slug])
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController

  skip_before_action :verify_authenticity_token, :only => [:create]

  def create
    if params[:zen]
      head :no_content
      return
    else
      pull_request = Adapters::GitHubWrapper.new.create_or_update_pr_from_webhook(params[:pull_request])
      WebHooksPullRequestUpdaterJob.perform_now(pull_request)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/pull_request_files_helper.rb
module PullRequestFilesHelper
end

app/helpers/pull_requests_helper.rb
module PullRequestsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironLabTrackr</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= favicon_link_tag 'flatiron_school_slashes_transparent_background.png' %>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
  </head>

  <body>

  <%= render 'shared/navbar' %>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Flatiron Lab Trackr", root_path, class: "navbar-brand"%>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li>
                <%= link_to "cohorts", cohorts_path%>
              </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= render 'shared/search_form' %>
            </li>
          </ul>
      </div>
    </div>
  </nav>

app/views/shared/_search_form.html.erb
<%= form_tag '/search', method: 'GET', class: 'navbar-form navbar-left', role: 'search' do %>
  <%= radio_button_tag :type, 'students', checked: true %>
  <%= label_tag :type_students, 'students', class: 'radio-label' %>
  <%= radio_button_tag :type, 'labs' %>
  <%= label_tag :type_labs, 'labs', class: 'radio-label' %>
  <%= collection_select :cohort, :id, Cohort.all, :id, :name, {}, { class: 'cohort-select' } %>
  <%= text_field_tag :query, '', class: 'form-control' %>
  <%= submit_tag 'Search', class: 'btn btn-default' %>
<% end %>